### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by robertd** [Daniel-ltw/ruby-node-alpine#3]
Hello,

In your dockerfile you're using `mhart-node:latest` but `v9.10.0` gets installed instead of `v10.4.0`. Am I missing something?

Thanks!

**Comment by Daniel-ltw** [comment]
I have not build the image recently and I did not put in automated build trigger for 'Linked Repositories' in my docker hub repo. 

Just added that in. I will also trigger all builds to run now. 

If you do think that there are further issues on this, feel free to come back and drop further comments.

**Comment by robertd** [comment]
Wow thanks for quick response. Looks good. Closing.

```bash
Step 8/10 : RUN node --version
 ---> Running in b2581720f6f0
v10.4.0
Removing intermediate container b2581720f6f0
 ---> 465246514d41
Step 9/10 : RUN ruby --version
 ---> Running in 072a54b82118
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
Removing intermediate container 072a54b82118
 ---> 9918b6feaeba
```

**Comment by Daniel-ltw** [comment]
All good.

**Comment by robertd** [comment]
@Daniel-ltw can you bump up node and ruby versions? Thx!

**Comment by Daniel-ltw** [comment]
Happy to merge a pull request in. 

Maybe change from mhart to https://hub.docker.com/_/node/
